version: "3"
services:
  spring-batch:
    image: addisu/addis-miniproject:latest
    container_name: addis-miniproject
    ports:
      - 8080:8082
    depends_on:
      - mysql-standalone
    environment:
      - spring_datasource_url=jdbc:mysql://mysqlcontainer:3306/batchprocessing?createDatabaseIfNotExist=true
  mysql-standalone:
    image: mysql:8
    container_name: mysqlcontainer
    environment:
      - MYSQL_ROOT_PASSWORD=pass1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass1234
      - MYSQL_DATABASE=batchprocessing